### ISSUE TITLE
helpers.py will not work without Shapely

### ISSUE THREAD

**Issue by GrazingScientist** [UW-xDD/table-extract#10]
The Developers removed the dependency to Shapely but missed to substitute its functions and classes from helpers.py.

As workaround, I recommend to add the removed imports in helpers.py and install shapely.

The exact code to insert can be seen in the commit log:
https://github.com/UW-Deepdive-Infrastructure/table-extract/commit/170086c41b1b081cd472aafacb3007a5762933a7

**Comment by milansegedinac** [comment]
Hi,
Was Shapely removed for some particular reason?

**Comment by jczaplew** [comment]
This has been resolved
