### ISSUE TITLE
preprocess.sh Errors

### ISSUE THREAD

**Issue by jenniferzhu** [UW-xDD/table-extract#8]
How to fix those errors? Thanks!
> ./preprocess.sh: line 14: gs: command not found
./preprocess.sh: line 19: parallel: command not found

**Comment by GrazingScientist** [comment]
You need to install these scripts on your OS.

On Linux (depending on your exact distribution): sudo apt-get install ghostscript parallel
On Mac (with Homebrew): brew install ghostscript parallel

**Comment by jczaplew** [comment]
Thanks for the answer @GrazingScientist!
